format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
unstable_features = true
use_small_heuristics = "Max"
wrap_comments = true

ignore = ["pkcs11-sys/src/pkcs11_unix.rs", "pkcs11-sys/src/pkcs11_windows.rs"]
